Fixes AttributeError 'NoneType' object has no attribute 'can_run' in help
Due to cmd being None when not found - so solution is to check for
falseyness and error